name: launch Typesript test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - run: |
          cd typescript
          npm install
          npm run test
      - name: mutation test
        continue-on-error: true
        run: |
          cd typescript
          npm install
          npx stryker run 
